export const LOGIN_LOADING = "LOGIN_LOADING";
export const LOGIN_SUCCESS = "LOGIN_SUCCESS";
export const LOGIN_LOADING_FALSE = "LOGIN_LOADING_FALSE";
export const LOGOUT = "LOGOUT";
export const REVOKED_TOKEN_ERROR_LOGOUT = "REVOKED_TOKEN_ERROR_LOGOUT";
export const RESET_ERROR_LOGOUT = "RESET_ERROR_LOGOUT";
