export const userCollapsedTable = {
  accounts: {
    employees: {
      index: false,
      show: false,
      create: false,
      update: false,
      destroy: false,
    },
    labs: {
      index: false,
      show: false,
      create: false,
      update: false,
      destroy: false,
    },
    roles: {
      index: false,
      show: false,
      create: false,
      update: false,
      destroy: false,
    },
    client: {
      index: false,
      show: false,
      create: false,
      update: false,
      destroy: false,
    },
    account_logs: {
      index: false,
      show: false,
      create: false,
      update: false,
      destroy: false,
    },
  },
  labs_module: {
    sample_reception: {
      index: false,
      show: false,
      create: false,
      update: false,
      destroy: false,
    },
    data_entry: {
      index: false,
      show: false,
      create: false,
      update: false,
      destroy: false,
    },
    resolution: {
      index: false,
      show: false,
      create: false,
      update: false,
      destroy: false,
    },
    lab_logs: {
      index: false,
      show: false,
      create: false,
      update: false,
      destroy: false,
    },
  },
  marketing_module: {
    tests: {
      index: false,
      show: false,
      create: false,
      update: false,
      destroy: false,
    },
    promotion: {
      index: false,
      show: false,
      create: false,
      update: false,
      destroy: false,
    },
    sales_funnel: {
      index: false,
      show: false,
      create: false,
      update: false,
      destroy: false,
    },
    marketing_logs: {
      index: false,
      show: false,
      create: false,
      update: false,
      destroy: false,
    },
  },
  logistics_module: {
    routes: {
      index: false,
      show: false,
      create: false,
      update: false,
      destroy: false,
    },
    riders: {
      index: false,
      show: false,
      create: false,
      update: false,
      destroy: false,
    },
    analytics: {
      index: false,
      show: false,
      create: false,
      update: false,
      destroy: false,
    },
    logistics_logs: {
      index: false,
      show: false,
      create: false,
      update: false,
      destroy: false,
    },
  },
  inventory_module: {
    operations: {
      index: false,
      show: false,
      create: false,
      update: false,
      destroy: false,
    },
    locations: {
      index: false,
      show: false,
      create: false,
      update: false,
      destroy: false,
    },
    stock: {
      index: false,
      show: false,
      create: false,
      update: false,
      destroy: false,
    },
    purchases_request: {
      index: false,
      show: false,
      create: false,
      update: false,
      destroy: false,
    },
    purchases_order: {
      index: false,
      show: false,
      create: false,
      update: false,
      destroy: false,
    },
    good_receipt: {
      index: false,
      show: false,
      create: false,
      update: false,
      destroy: false,
    },
    credit_note: {
      index: false,
      show: false,
      create: false,
      update: false,
      destroy: false,
    },
    back_note: {
      index: false,
      show: false,
      create: false,
      update: false,
      destroy: false,
    },
    stock_transfer: {
      index: false,
      show: false,
      create: false,
      update: false,
      destroy: false,
    },
    stock_return: {
      index: false,
      show: false,
      create: false,
      update: false,
      destroy: false,
    },
    cycle_count: {
      index: false,
      show: false,
      create: false,
      update: false,
      destroy: false,
    },
    inventory_logs: {
      index: false,
      show: false,
      create: false,
      update: false,
      destroy: false,
    },
  },
  crm_module: {
    call_center: {
      index: false,
      show: false,
      create: false,
      update: false,
      destroy: false,
    },
    crm_logs: {
      index: false,
      show: false,
      create: false,
      update: false,
      destroy: false,
    },
  },
};
